name: AI Agent
system_prompt:
  - 你是一个专业的股票市场分析师，提供详细的股票和市场趋势分析，可以通过提供个工具/tools接口来获取股票和市场数据，以提供更准确的分析，和完善的内容。
  - 在调用工具/tools时前，需要首先确定今天的日期和时间，以确保在调用工具/tools时传入正确的数据。
  - 你需要正确判断请求中的各种日期内容，如‘今天’在日期/date上是今天的‘YYYY-MM-DD’，‘三个月’是指‘最近的三个月’等。
  - >-
    请求中要求图表输出或应答中含有图标输出时，以JSON格式返回图表数据所需的参数信息，不需要返回具体图表的数据，内容参考示例：```json { "info": { "type": 2, "code": "0000001", "start": "2020-01-01", "end": "2020-05-01", "period": "daily", "chart": { "type": "kline", "xAxis": ["日期"], "yAxis": ["K线数据"] } } } ```, 示例中`chart`的`type`可选值为`kline`/`line`/`bar`/`candlestick`/`mixed`，用于指示图表类型， `yAxis`为图表的Y轴数据指示，可以是多个，如[`K线数据`,`成交量`]，并在输出前添加`\n// @echart-option start`，在输出后添加`\n// @echart-option end`，用于前端获取图表配置后进行渲染。
model: deepseek-chat
temperature: 0.7
top_p: 1.0
top_k: 0
max_tokens: 2000
tools:
  - module: app.services.agent.fetch_data
    name: get_type
    description: Get the type value for a given category.
    parameters:
      type: object
      properties:
        category:
          type: string
          description: >-
            category: Category string - '指数'/'index' for index, '股票'/'stock' for stock
      required:
        - category
    enabled: true
  - module: app.services.agent.fetch_data
    name: get_history_data
    description: Get K-line/history data for a specified stock.
    parameters:
      type: object
      properties:
        type:
          type: integer
          description: Stock or Index type, 1 for index, 2 for stock
        code:
          type: string
          description: Stock or Index code
        start:
          type: string
          description: Start date, formatted as YYYY-MM-DD
        end:
          type: string
          description: End date, formatted as YYYY-MM-DD
        period:
          type: string
          description: Data period, default 'daily'
        adjust:
          type: string
          description: Adjust type, default 'qfq'
        limit:
          type: integer
          description: Data limit, default 100
        record_flag:
          type: integer
          description: 0 for normal check & update, 1 for disabled, default 0
      required:
        - type
        - code
    enabled: true
  - module: app.services.agent.fetch_data
    name: record
    description: Get detailed holding stock records, includes type, code and name, etc.
    parameters:
      type: object
      properties:
        type:
          type: integer
          description: Stock or Index type, 1 for index, 2 for stock
        code:
          type: string
          description: Stock or Index code
      required: []
    enabled: true
memory:
  max_history: 10
  memory_type: message_window
  enabled: true
