import pandas as pd
import talib

defaultOptions = {
  'timeperiod': 14,
  'column_high': '最高',
  'column_low': '最低',
  'column_close': '收盘'
}

def title() -> str:
  return "Normalized Average True Range (NATR) - 归一化平均真实波幅"

def calc(history_data: pd.DataFrame, options: dict = defaultOptions) -> pd.DataFrame:
  """
  根据提供的历史数据和选项计算归一化平均真实波幅(NATR)。
  Args:
      history_data (pd.DataFrame): 包含历史价格数据的数据集。
                                   必须包含 '最高', '最低', '收盘' 列。
      options (dict): 包含以下键的字典:
                      - 'timeperiod': NATR的计算周期 (默认: 14)
                      - 'column_high': 最高价列名 (默认: '最高')
                      - 'column_low': 最低价列名 (默认: '最低')
                      - 'column_close': 收盘价列名 (默认: '收盘')
  Returns:
      pd.DataFrame: 包含以下列的DataFrame:
      - 'NATR': NATR值
      - 'Signal': 信号 (1: 高波动, -1: 低波动, 0: 中性)
  """
  options = defaultOptions | options
  natr = talib.NATR(history_data[options['column_high']],
                  history_data[options['column_low']],
                  history_data[options['column_close']],
                  timeperiod=options['timeperiod'])

  result = pd.DataFrame({
      'NATR': natr
  })

  # Signal generation: Simple threshold for normalized volatility
  # Similar to ATR, NATR is a volatility measure. Signals can be generated by comparing to its moving average or fixed thresholds.
  result['Signal'] = 0
  mean_natr = natr.rolling(window=options['timeperiod']).mean()
  result.loc[natr > mean_natr * 1.2, 'Signal'] = 1  # High normalized volatility
  result.loc[natr < mean_natr * 0.8, 'Signal'] = -1 # Low normalized volatility

  return result

def report(history_data: pd.DataFrame, natr_data: pd.DataFrame, idx: int = 0, options: dict = defaultOptions) -> list[dict]:
  options = defaultOptions | options

  result: list[dict] = []

  signal_points = natr_data[(natr_data['Signal'] == 1) | (natr_data['Signal'] == -1)]

  if idx == 0:
      selected_points = signal_points
  elif idx < 0:
      selected_points = signal_points.tail(abs(idx))
  else: # idx > 0
      selected_points = signal_points.iloc[idx-1:]

  for i, row in selected_points.iterrows():
      result.append({
          "index": str(i),
          "price": float(history_data.loc[i, options['column_close']]),
          "trend": int(row['Signal'])
      })

  return result
