version: "3.8"
name: batman
services:
  app:
    container_name: app
    image: batman:app
    ports:
      - "9000:9000"
    volumes:
      - ../app/db:/batman/app/db
    environment:
      - PORT=9000
    networks:
      - batman

  signal:
    container_name: signal
    image: batman:signal
    ports:
      - "3030:3030"
    depends_on:
      - app
    networks:
      - batman
      
networks:
  batman:
    driver: bridge