# version: "3.8"
name: batman
services:
  app:
    container_name: app
    image: codejie/batman:app
    ports:
      - "8000:8000"
    volumes:
      - ../app/db:/batman/app/db # compose start under deploy folder
    environment:
      - PORT=8000
    networks:
      - batman

  signal:
    container_name: signal
    image: codejie/batman:signal
    ports:
      - "3030:3030"
    depends_on:
      - app
    networks:
      - batman
      
networks:
  batman:
    driver: bridge